"""empty message

Revision ID: 2aee9fd1bff5
Revises: 7721d56effd0
Create Date: 2021-08-24 19:19:29.156777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2aee9fd1bff5'
down_revision = '7721d56effd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('fecha', sa.DateTime(), nullable=True))
    op.add_column('persona', sa.Column('tecnico', sa.String(length=250), nullable=True))
    op.add_column('persona', sa.Column('serie_numero', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('dosis_total', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('numero_sesiones', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('porcentaje_pauta', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('Movimientos', sa.String(length=250), nullable=True))
    op.add_column('persona', sa.Column('tac_lateral', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('tac_ant_post', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('tac_sup_inf', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('iso_lateral', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('iso_ant_post', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('iso_sup_inf', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('norm_lateral', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('norm_ant_post', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('norm_sup_inf', sa.Float(), nullable=True))
    op.add_column('persona', sa.Column('numero_campos', sa.Integer(), nullable=True))
    op.drop_column('persona', 'email')
    op.add_column('tratamiento', sa.Column('id_paciente', sa.Integer(), nullable=True))
    op.drop_constraint('tratamiento_dni_paciente_fkey', 'tratamiento', type_='foreignkey')
    op.create_foreign_key(None, 'tratamiento', 'persona', ['id_paciente'], ['id'])
    op.drop_column('tratamiento', 'norm_lateral')
    op.drop_column('tratamiento', 'dosis_total')
    op.drop_column('tratamiento', 'tac_ant_post')
    op.drop_column('tratamiento', 'iso_lateral')
    op.drop_column('tratamiento', 'norm_ant_post')
    op.drop_column('tratamiento', 'serie_numero')
    op.drop_column('tratamiento', 'tecnico')
    op.drop_column('tratamiento', 'fecha_tto')
    op.drop_column('tratamiento', 'dni_paciente')
    op.drop_column('tratamiento', 'Movimientos')
    op.drop_column('tratamiento', 'tac_lateral')
    op.drop_column('tratamiento', 'norm_sup_inf')
    op.drop_column('tratamiento', 'tac_sup_inf')
    op.drop_column('tratamiento', 'iso_sup_inf')
    op.drop_column('tratamiento', 'porcentaje_pauta')
    op.drop_column('tratamiento', 'numero_sesiones')
    op.drop_column('tratamiento', 'iso_ant_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('iso_ant_post', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('numero_sesiones', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('porcentaje_pauta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('iso_sup_inf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('tac_sup_inf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('norm_sup_inf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('tac_lateral', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('Movimientos', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('dni_paciente', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('fecha_tto', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('tecnico', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('serie_numero', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('norm_ant_post', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('iso_lateral', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('tac_ant_post', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('dosis_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tratamiento', sa.Column('norm_lateral', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tratamiento', type_='foreignkey')
    op.create_foreign_key('tratamiento_dni_paciente_fkey', 'tratamiento', 'persona', ['dni_paciente'], ['id'])
    op.drop_column('tratamiento', 'id_paciente')
    op.add_column('persona', sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('persona', 'numero_campos')
    op.drop_column('persona', 'norm_sup_inf')
    op.drop_column('persona', 'norm_ant_post')
    op.drop_column('persona', 'norm_lateral')
    op.drop_column('persona', 'iso_sup_inf')
    op.drop_column('persona', 'iso_ant_post')
    op.drop_column('persona', 'iso_lateral')
    op.drop_column('persona', 'tac_sup_inf')
    op.drop_column('persona', 'tac_ant_post')
    op.drop_column('persona', 'tac_lateral')
    op.drop_column('persona', 'Movimientos')
    op.drop_column('persona', 'porcentaje_pauta')
    op.drop_column('persona', 'numero_sesiones')
    op.drop_column('persona', 'dosis_total')
    op.drop_column('persona', 'serie_numero')
    op.drop_column('persona', 'tecnico')
    op.drop_column('persona', 'fecha')
    # ### end Alembic commands ###
