"""empty message

Revision ID: 3495b1ec0a4b
Revises: 5fb6a88476ff
Create Date: 2021-09-10 23:05:59.316770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3495b1ec0a4b'
down_revision = '5fb6a88476ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=True),
    sa.Column('clave_usuario', sa.String(length=100), nullable=True),
    sa.Column('rol_usuario', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
