"""empty message

Revision ID: 5e6b12ef42e3
Revises: c078c77366d2
Create Date: 2021-08-21 20:16:14.535413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6b12ef42e3'
down_revision = 'c078c77366d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('dni', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'dni')
    # ### end Alembic commands ###
