"""empty message

Revision ID: 70de669640b3
Revises: 2aee9fd1bff5
Create Date: 2021-08-28 16:41:24.574492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70de669640b3'
down_revision = '2aee9fd1bff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('id_campo', sa.Integer(), nullable=False))
    op.add_column('tratamiento', sa.Column('num_campo', sa.Integer(), nullable=True))
    op.add_column('tratamiento', sa.Column('nombre_campo', sa.String(length=250), nullable=True))
    op.add_column('tratamiento', sa.Column('gantry', sa.Integer(), nullable=True))
    op.add_column('tratamiento', sa.Column('colimador', sa.Integer(), nullable=True))
    op.add_column('tratamiento', sa.Column('mesa', sa.Integer(), nullable=True))
    op.add_column('tratamiento', sa.Column('energia', sa.String(length=250), nullable=True))
    op.add_column('tratamiento', sa.Column('dfp_a_norm', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('tecnica', sa.String(length=250), nullable=True))
    op.add_column('tratamiento', sa.Column('Y2', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('Y1', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('X2', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('X1', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('dL_offset', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('dW_offset', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('x_isoc', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('y_isoc', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('cuadrado_equi', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('porcentaje_bloqueo', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('campo_equivalente', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('conformacion', sa.String(length=250), nullable=True))
    op.add_column('tratamiento', sa.Column('prof_fisica', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('prof_equiv', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('cunyya', sa.String(length=250), nullable=True))
    op.add_column('tratamiento', sa.Column('dose_at_ref_frac', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('porcentaje_normalizacion', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('dosis_cGy', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('dosis_referencia', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('pdd_10', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('sc_isoc', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('sp_isoc', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('tpr', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('f_cunya_fuera_eje', sa.Integer(), nullable=True))
    op.add_column('tratamiento', sa.Column('oar', sa.Integer(), nullable=True))
    op.add_column('tratamiento', sa.Column('um_hoja', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('um_pinnacle', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('diferencia_porcentaje', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('um_aria', sa.Integer(), nullable=True))
    op.add_column('tratamiento', sa.Column('aria_pinnacle', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('error_verificacion', sa.Float(), nullable=True))
    op.add_column('tratamiento', sa.Column('error_redondeo_de_um', sa.Float(), nullable=True))
    op.drop_column('tratamiento', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('tratamiento', 'error_redondeo_de_um')
    op.drop_column('tratamiento', 'error_verificacion')
    op.drop_column('tratamiento', 'aria_pinnacle')
    op.drop_column('tratamiento', 'um_aria')
    op.drop_column('tratamiento', 'diferencia_porcentaje')
    op.drop_column('tratamiento', 'um_pinnacle')
    op.drop_column('tratamiento', 'um_hoja')
    op.drop_column('tratamiento', 'oar')
    op.drop_column('tratamiento', 'f_cunya_fuera_eje')
    op.drop_column('tratamiento', 'tpr')
    op.drop_column('tratamiento', 'sp_isoc')
    op.drop_column('tratamiento', 'sc_isoc')
    op.drop_column('tratamiento', 'pdd_10')
    op.drop_column('tratamiento', 'dosis_referencia')
    op.drop_column('tratamiento', 'dosis_cGy')
    op.drop_column('tratamiento', 'porcentaje_normalizacion')
    op.drop_column('tratamiento', 'dose_at_ref_frac')
    op.drop_column('tratamiento', 'cunyya')
    op.drop_column('tratamiento', 'prof_equiv')
    op.drop_column('tratamiento', 'prof_fisica')
    op.drop_column('tratamiento', 'conformacion')
    op.drop_column('tratamiento', 'campo_equivalente')
    op.drop_column('tratamiento', 'porcentaje_bloqueo')
    op.drop_column('tratamiento', 'cuadrado_equi')
    op.drop_column('tratamiento', 'y_isoc')
    op.drop_column('tratamiento', 'x_isoc')
    op.drop_column('tratamiento', 'dW_offset')
    op.drop_column('tratamiento', 'dL_offset')
    op.drop_column('tratamiento', 'X1')
    op.drop_column('tratamiento', 'X2')
    op.drop_column('tratamiento', 'Y1')
    op.drop_column('tratamiento', 'Y2')
    op.drop_column('tratamiento', 'tecnica')
    op.drop_column('tratamiento', 'dfp_a_norm')
    op.drop_column('tratamiento', 'energia')
    op.drop_column('tratamiento', 'mesa')
    op.drop_column('tratamiento', 'colimador')
    op.drop_column('tratamiento', 'gantry')
    op.drop_column('tratamiento', 'nombre_campo')
    op.drop_column('tratamiento', 'num_campo')
    op.drop_column('tratamiento', 'id_campo')
    # ### end Alembic commands ###
