"""empty message

Revision ID: bd0891f4469c
Revises: 6036445771c5
Create Date: 2021-08-29 17:38:57.683029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0891f4469c'
down_revision = '6036445771c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tratamiento', 'num_campo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tratamiento', 'num_campo',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
